version: 2.1

jobs:
  build-glibc:
    docker:
      - image: gcc
    steps:
      - checkout
      - run: make

  build-musl:
    docker:
      - image: gcc
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y musl musl-dev musl-tools
      - run:
          environment:
            CC: musl-gcc
          command: make static

workflows:
  build-glibc:
    jobs:
      - build-glibc
  build-musl:
    jobs:
      - build-musl
